### ISSUE TITLE
Configure vitest

### ISSUE THREAD

**Issue by geovane-gc** [geovane-gc/lets-help-rs#1]
We're going to use Vitest in this project. It's already installed but we still need to configure it. You can see the docs <a href="https://vitest.dev/guide/">here</a>.

MOST IMPORTANT: coverage.

**Comment by joojscript** [comment]
✅ Addressed here: https://github.com/geovane-gc/lets-help-rs/pull/8/commits/743d115880416daf8a16d9465b7000c33db2c6d2

**Comment by joojscript** [comment]
PR: https://github.com/geovane-gc/lets-help-rs/pull/8
